<?php
use App\Controllers\SpeakerController;
use App\Core\Auth;
use App\Core\Csrf;
use App\Core\View;

$csrf=Csrf::getToken();
$roundId=(int)$round['id'];
$drawId=(int)($round['draw_id'] ?? $draw['id'] ?? 0);
$calledSet=array_fill_keys(array_map('intval',$calledNumbers ?? []),true);
$speakerToken=SpeakerController::generateSpeakerToken($roundId,(string)($round['operation_date'] ?? ''));
$shareUrl=$speakerToken!==''?'https://showdepremios.mskpoeira.com.br/locutor?id='.$roundId.'&speaker_token='.rawurlencode($speakerToken):'';
$status=(string)($round['status'] ?? 'OPEN');
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= View::e($title) ?></title><style>
*{box-sizing:border-box}body{margin:0;background:#07101f;color:#fff;font-family:Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.badge{background:#1e293b;border:1px solid #475569;border-radius:999px;padding:7px 12px;font-weight:800}.last{text-align:center;margin:12px 0;padding:12px;border:2px solid #2563eb;border-radius:14px;background:#0f172a}.last .value{font-size:clamp(3rem,10vw,7rem);font-weight:1000;line-height:1}.board{display:grid;grid-template-columns:repeat(15,1fr);gap:6px}.ball{aspect-ratio:1;border-radius:50%;border:1px solid #475569;background:#172033;color:#e2e8f0;font-weight:800;cursor:pointer}.ball.called{background:#2563eb;border-color:#93c5fd}.ball:disabled{cursor:not-allowed}.controls,.card{background:#0f172a;border:1px solid #334155;border-radius:12px;padding:12px;margin-top:12px}.controls{display:flex;gap:8px;flex-wrap:wrap}.controls input,.card input,.card select{padding:9px;border-radius:7px;border:1px solid #64748b;background:#111827;color:#fff}.btn{padding:9px 12px;border:0;border-radius:7px;font-weight:800;cursor:pointer}.primary{background:#2563eb;color:#fff}.danger{background:#b91c1c;color:#fff}.warn{background:#d97706;color:#fff}.success{background:#15803d;color:#fff}.muted{background:#475569;color:#fff}.checking{border-color:#f59e0b;background:#451a03}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.board{grid-template-columns:repeat(10,1fr)}.grid2{grid-template-columns:1fr}}@media(max-width:500px){.board{grid-template-columns:repeat(5,1fr)}}
</style></head><body><div class="wrap">
<div class="top"><div><h1 style="margin:.2rem 0">🎤 Locutor — Rodada <?= (int)$round['round_number'] ?></h1><div><?= View::e($round['round_name'] ?? '') ?> • <?= View::e($round['card_color'] ?? '') ?></div></div><div class="badge" id="statusBadge"><?= View::e($status) ?></div></div>
<div class="last"><div>ÚLTIMA PEDRA</div><div class="value"><span id="lastLetter"><?= !empty($round['last_called_number'])?View::e(SpeakerController::getLetterForNumber((int)$round['last_called_number'])):'—' ?></span>-<span id="lastNumber"><?= !empty($round['last_called_number'])?(int)$round['last_called_number']:'—' ?></span></div><div>Chamadas: <strong id="totalCalled"><?= count($calledNumbers ?? []) ?></strong>/75</div></div>
<div class="board" id="board"><?php for($n=1;$n<=75;$n++):?><button class="ball <?= isset($calledSet[$n])?'called':'' ?>" id="ball-<?= $n ?>" data-number="<?= $n ?>" <?= isset($calledSet[$n])?'disabled':'' ?>><?= $n ?></button><?php endfor;?></div>
<div class="controls"><input type="number" min="1" max="75" id="manualNumber" placeholder="Número"><button class="btn primary" id="callManual">Cantar número</button><button class="btn primary" id="randomBtn">🎲 Sortear aleatório</button><button class="btn warn" id="autoBtn">▶ Automático</button><button class="btn muted" id="undoBtn">↩ Desfazer última</button><button class="btn muted" id="pauseBtn">⏸ Pausar</button></div>
<div id="checkingBox" class="card checking" style="<?= $status==='CHECKING'?'':'display:none' ?>"><strong>🔔 CONFERÊNCIA</strong><p>O sorteio está em conferência. Candidatos digitais não são homologados automaticamente. Aceite também reivindicações de cartelas físicas e finalize somente pelo botão de homologação autorizado.</p></div>
<div class="grid2">
<div class="card"><h3>🧾 Conferir cartela física</h3><p>Registre somente após conferir a cartela física contra as pedras oficiais.</p><input id="physicalName" placeholder="Nome ou PORTADOR DA CARTELA"><input id="physicalSeller" placeholder="Vendedor / observação"><button class="btn success" id="physicalBtn">Registrar para homologação</button></div>
<div class="card"><h3>📲 Acesso seguro do locutor</h3><?php if($shareUrl!==''):?><p>Link válido para esta rodada/data, assinado com a chave da aplicação:</p><input id="shareUrl" readonly value="<?= View::e($shareUrl) ?>" style="width:100%"><button class="btn primary" onclick="navigator.clipboard.writeText(document.getElementById('shareUrl').value)">Copiar link</button><?php else:?><p style="color:#fca5a5">Configure APP_KEY forte no servidor para habilitar link seguro do locutor.</p><?php endif; ?></div>
</div>
<?php if(Auth::isAdmin()):?><div class="card"><h3>🔐 Homologação administrativa</h3><button class="btn success" id="homologateBtn">✅ HOMOLOGAR RESULTADO</button><button class="btn danger" id="resetBtn">🧹 Reiniciar sorteio (somente sem homologação)</button></div><?php endif; ?>
</div>
<script>
const csrf=<?= json_encode($csrf) ?>,roundId=<?= $roundId ?>,drawId=<?= $drawId ?>,speakerToken=<?= json_encode($speakerToken) ?>;let autoTimer=null,busy=false;
function body(data){return new URLSearchParams(Object.assign({_csrf_token:csrf,round_id:String(roundId),speaker_token:speakerToken},data));}
async function post(url,data={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json','X-CSRF-Token':csrf},body:body(data),cache:'no-store'});const j=await r.json().catch(()=>({success:false,error:'Resposta inválida do servidor.'}));if(!r.ok||j.success===false)throw new Error(j.error||j.message||'Operação recusada.');return j;}
function mark(n){const el=document.getElementById('ball-'+n);if(el){el.classList.add('called');el.disabled=true}}
function unmark(n){const el=document.getElementById('ball-'+n);if(el){el.classList.remove('called');el.disabled=false}}
function setStatus(s){document.getElementById('statusBadge').textContent=s;document.getElementById('checkingBox').style.display=s==='CHECKING'?'':'none';}
async function callNumber(n){if(busy||n<1||n>75)return;busy=true;try{const j=await post('/locutor/cantar-pedra',{number:String(n)});mark(n);document.getElementById('lastLetter').textContent=j.letter||'';document.getElementById('lastNumber').textContent=n;document.getElementById('totalCalled').textContent=j.total_called??'';setStatus(j.status||'IN_PROGRESS');if(j.requires_homologation){stopAuto();alert('Conferência necessária. Verifique candidatos digitais e eventuais cartelas físicas antes da homologação.');}}catch(e){alert(e.message)}finally{busy=false}}
function randomRemaining(){const rem=[];document.querySelectorAll('.ball:not(.called)').forEach(b=>rem.push(Number(b.dataset.number)));if(!rem.length)return null;const a=new Uint32Array(1);crypto.getRandomValues(a);return rem[a[0]%rem.length];}
function stopAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null;}document.getElementById('autoBtn').textContent='▶ Automático';}
document.querySelectorAll('.ball').forEach(b=>b.addEventListener('click',()=>callNumber(Number(b.dataset.number))));
document.getElementById('callManual').onclick=()=>callNumber(Number(document.getElementById('manualNumber').value));document.getElementById('randomBtn').onclick=()=>{const n=randomRemaining();if(n)callNumber(n)};document.getElementById('autoBtn').onclick=()=>{if(autoTimer){stopAuto();return;}document.getElementById('autoBtn').textContent='■ Parar automático';autoTimer=setInterval(()=>{const n=randomRemaining();if(n)callNumber(n);else stopAuto()},5000)};
document.getElementById('undoBtn').onclick=async()=>{stopAuto();try{const j=await post('/locutor/desfazer-pedra');unmark(j.removed_number);document.getElementById('lastNumber').textContent=j.last_called_number||'—';document.getElementById('lastLetter').textContent=j.last_letter||'—';document.getElementById('totalCalled').textContent=j.total_called??0}catch(e){alert(e.message)}};
document.getElementById('pauseBtn').onclick=async()=>{stopAuto();try{const j=await post('/locutor/alterar-status',{status:'PAUSED'});setStatus(j.status)}catch(e){alert(e.message)}};
document.getElementById('physicalBtn').onclick=async()=>{stopAuto();const name=document.getElementById('physicalName').value.trim()||'PORTADOR DA CARTELA';const seller=document.getElementById('physicalSeller').value.trim();try{const j=await post('/locutor/salvar-ganhador',{winner_name:name,seller_name:seller,prize_index:'1'});setStatus('CHECKING');alert(j.message)}catch(e){alert(e.message)}};
<?php if(Auth::isAdmin()):?>document.getElementById('homologateBtn').onclick=async()=>{if(!confirm('Homologar oficialmente todos os ganhadores pendentes desta pedra?'))return;try{const j=await post('/sorteio/homologar',{draw_id:String(drawId)});setStatus(j.status||'CLOSED');alert(j.message)}catch(e){alert(e.message)}};document.getElementById('resetBtn').onclick=async()=>{if(!confirm('Reiniciar todas as pedras deste sorteio? Esta ação é bloqueada se houver resultado homologado.'))return;try{const j=await post('/locutor/limpar-pedras');location.reload()}catch(e){alert(e.message)}};<?php endif;?>
</script></body></html>
